import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather, Neuton, Slabo_13px } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import vercelLogo from "../public/vercel.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center p-4 bg-gray-800 text-white">
          <Image src={vercelLogo} alt="Vercel Logo" width={32} height={32} />
          <Link href="/" className="ml-2 text-xl font-bold">
            Colony-AI
          </Link>
          <Link href="/about" className="ml-auto ml-4 text-lg">
            About
          </Link>
          <Link href="/contact" className="ml-4 text-lg">
            Contact
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
